--enable-features=VaapiVideoDecoder,AcceleratedVideoDecodeLinuxGL,AcceleratedVideoDecodeLinuxZeroCopyGL,VaapiOnNvidiaGPUs,VaapiIgnoreDriverChecks,WaylandLinuxDrmSyncobj
--ignore-gpu-blocklist
--ozone-platform=wayland
